name: RISC-V Assmebly Instruction Translate and Decoding

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install GCC
        run: sudo apt-get install -y gcc

      - name: Compile C File
        run: gcc main.c -o main

      - name: Input wrong file name
        run: echo -e "some_file.s\nterminate" | ./main

      - name: Run Compiled Program
        run: echo -e "test1.s\ntest2.s\ntest3.s\nterminate" | ./main

      - name: Print test1.o diff
        run: diff test1.o test1_answer.o

      - name: Print test1.trace diff
        run: diff test1.trace test1_answer.trace

      - name: Check test1.o
        run: |
          if diff -q test1.o test1_answer.o; then
            echo "test1.o success."
          else
            echo "test1.o fail."
            exit 1
          fi

      - name: Check test1.trace
        run: |
          if diff -q test1.trace test1_answer.trace; then
            echo "test1.trace success."
          else
            echo "test1.trace fail."
            exit 1
          fi

      - name: Print test2.o diff
        run: diff test2.o test2_answer.o

      - name: Print test2.trace diff
        run: diff test2.trace test2_answer.trace

      - name: Check test2.o
        run: |
          if diff -q test2.o test2_answer.o; then
            echo "test2.o success."
          else
            echo "test2.o fail."
            exit 1
          fi
      - name: Check test2.trace
        run: |
          if diff -q test2.trace test2_answer.trace; then
            echo "test2.trace success."
          else
            echo "test2.trace fail."
            exit 1
          fi

      - name: Print test3.o diff
        run: diff test3.o test3_answer.o

      - name: Print test3.trace diff
        run: diff test3.trace test3_answer.trace

      - name: Check test3.o
        run: |
          if diff -q test3.o test3_answer.o; then
            echo "test3.o success."
          else
            echo "test3.o fail."
            exit 1
          fi

      - name: Check test3.trace
        run: |
          if diff -q test3.trace test3_answer.trace; then
            echo "test3.trace success"
          else
            echo "test3.trace fail"
            exit 1
          fi