name: RISC-V Assmebly Instruction Translate and Decoding

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install GCC
      run: sudo apt-get install -y gcc

    - name: Compile C File
      run: gcc main.c -o main

    - name: Run Compiled Program
      run: echo -e "test1.s\ntest2.s\ntest3.s\nterminate" | ./main