name: RISC-V Assembly Instruction Translate and Decoding

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 초기 설정 단계
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install GCC
        run: sudo apt-get install -y gcc

      - name: Compile C File
        run: gcc main.c -o main

      # 잘못된 파일 이름 테스트
      - name: Input wrong file name
        run: echo -e "some_file.s\nterminate" | ./main

      # 모든 테스트 케이스 실행
      - name: Run Compiled Program
        run: echo -e "test1.s\ntest2.s\ntest3.s\ntestcase1.s\ntestcase2.s\ntestcase3.s\ntestcase4.s\ntestcase5.s\ntestcase6.s\ntestcase7.s\ntestcase8-1.s\ntestcase8-2.s\ntestcase8-3.s\nterminate" | ./main

      # [이전 테스트 케이스들은 동일하게 유지... test1부터 testcase7까지]

      # 새로운 테스트 케이스 8-1
      - name: Print testcase8-1.o diff
        run: diff testcase8-1.o testcase8-1_ans.o

      - name: Print testcase8-1.trace diff
        run: diff testcase8-1.trace testcase8-1_ans.trace

      - name: Check testcase8-1.o
        run: |
          if diff -q testcase8-1.o testcase8-1_ans.o; then
            echo "testcase8-1.o success."
          else
            echo "testcase8-1.o fail."
            exit 1
          fi

      - name: Check testcase8-1.trace
        run: |
          if diff -q testcase8-1.trace testcase8-1_ans.trace; then
            echo "testcase8-1.trace success."
          else
            echo "testcase8-1.trace fail."
            exit 1
          fi

      # 새로운 테스트 케이스 8-2
      - name: Print testcase8-2.o diff
        run: diff testcase8-2.o testcase8-2_ans.o

      - name: Print testcase8-2.trace diff
        run: diff testcase8-2.trace testcase8-2_ans.trace

      - name: Check testcase8-2.o
        run: |
          if diff -q testcase8-2.o testcase8-2_ans.o; then
            echo "testcase8-2.o success."
          else
            echo "testcase8-2.o fail."
            exit 1
          fi

      - name: Check testcase8-2.trace
        run: |
          if diff -q testcase8-2.trace testcase8-2_ans.trace; then
            echo "testcase8-2.trace success."
          else
            echo "testcase8-2.trace fail."
            exit 1
          fi

      # 새로운 테스트 케이스 8-3
      - name: Print testcase8-3.o diff
        run: diff testcase8-3.o testcase8-3_ans.o

      - name: Print testcase8-3.trace diff
        run: diff testcase8-3.trace testcase8-3_ans.trace

      - name: Check testcase8-3.o
        run: |
          if diff -q testcase8-3.o testcase8-3_ans.o; then
            echo "testcase8-3.o success."
          else
            echo "testcase8-3.o fail."
            exit 1
          fi

      - name: Check testcase8-3.trace
        run: |
          if diff -q testcase8-3.trace testcase8-3_ans.trace; then
            echo "testcase8-3.trace success."
          else
            echo "testcase8-3.trace fail."
            exit 1
          fi