name: RISC-V Assembly Instruction Translate and Decoding

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 초기 설정 단계
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install GCC
        run: sudo apt-get install -y gcc

      - name: Compile C File
        run: gcc main.c -o main

      # 잘못된 파일 이름 테스트
      - name: Input wrong file name
        run: echo -e "some_file.s\nterminate" | ./main

      # 모든 테스트 케이스 실행
      - name: Run Compiled Program
        run: echo -e "test1.s\ntest2.s\ntest3.s\ntestcase1.s\ntestcase2.s\ntestcase3.s\ntestcase4.s\ntestcase5.s\ntestcase6.s\ntestcase7.s\nterminate" | ./main

      # 기존 테스트 케이스 1
      - name: Print test1.o diff
        run: diff test1.o test1_answer.o

      - name: Print test1.trace diff
        run: diff test1.trace test1_answer.trace

      - name: Check test1.o
        run: |
          if diff -q test1.o test1_answer.o; then
            echo "test1.o success."
          else
            echo "test1.o fail."
            exit 1
          fi

      - name: Check test1.trace
        run: |
          if diff -q test1.trace test1_answer.trace; then
            echo "test1.trace success."
          else
            echo "test1.trace fail."
            exit 1
          fi

      # 기존 테스트 케이스 2
      - name: Print test2.o diff
        run: diff test2.o test2_answer.o

      - name: Print test2.trace diff
        run: diff test2.trace test2_answer.trace

      - name: Check test2.o
        run: |
          if diff -q test2.o test2_answer.o; then
            echo "test2.o success."
          else
            echo "test2.o fail."
            exit 1
          fi

      - name: Check test2.trace
        run: |
          if diff -q test2.trace test2_answer.trace; then
            echo "test2.trace success."
          else
            echo "test2.trace fail."
            exit 1
          fi

      # 기존 테스트 케이스 3
      - name: Print test3.o diff
        run: diff test3.o test3_answer.o

      - name: Print test3.trace diff
        run: diff test3.trace test3_answer.trace

      - name: Check test3.o
        run: |
          if diff -q test3.o test3_answer.o; then
            echo "test3.o success."
          else
            echo "test3.o fail."
            exit 1
          fi

      - name: Check test3.trace
        run: |
          if diff -q test3.trace test3_answer.trace; then
            echo "test3.trace success."
          else
            echo "test3.trace fail."
            exit 1
          fi

      # 새로운 테스트 케이스 1
      - name: Print testcase1.o diff
        run: diff testcase1.o testcase1_answer.o

      - name: Print testcase1.trace diff
        run: diff testcase1.trace testcase1_answer.trace

      - name: Check testcase1.o
        run: |
          if diff -q testcase1.o testcase1_answer.o; then
            echo "testcase1.o success."
          else
            echo "testcase1.o fail."
            exit 1
          fi

      - name: Check testcase1.trace
        run: |
          if diff -q testcase1.trace testcase1_answer.trace; then
            echo "testcase1.trace success."
          else
            echo "testcase1.trace fail."
            exit 1
          fi

      # 새로운 테스트 케이스 2
      - name: Print testcase2.o diff
        run: diff testcase2.o testcase2_answer.o

      - name: Print testcase2.trace diff
        run: diff testcase2.trace testcase2_answer.trace

      - name: Check testcase2.o
        run: |
          if diff -q testcase2.o testcase2_answer.o; then
            echo "testcase2.o success."
          else
            echo "testcase2.o fail."
            exit 1
          fi

      - name: Check testcase2.trace
        run: |
          if diff -q testcase2.trace testcase2_answer.trace; then
            echo "testcase2.trace success."
          else
            echo "testcase2.trace fail."
            exit 1
          fi

      # 새로운 테스트 케이스 3
      - name: Print testcase3.o diff
        run: diff testcase3.o testcase3_answer.o

      - name: Print testcase3.trace diff
        run: diff testcase3.trace testcase3_answer.trace

      - name: Check testcase3.o
        run: |
          if diff -q testcase3.o testcase3_answer.o; then
            echo "testcase3.o success."
          else
            echo "testcase3.o fail."
            exit 1
          fi

      - name: Check testcase3.trace
        run: |
          if diff -q testcase3.trace testcase3_answer.trace; then
            echo "testcase3.trace success."
          else
            echo "testcase3.trace fail."
            exit 1
          fi

      # 새로운 테스트 케이스 4
      - name: Print testcase4.o diff
        run: diff testcase4.o testcase4_answer.o

      - name: Print testcase4.trace diff
        run: diff testcase4.trace testcase4_answer.trace

      - name: Check testcase4.o
        run: |
          if diff -q testcase4.o testcase4_answer.o; then
            echo "testcase4.o success."
          else
            echo "testcase4.o fail."
            exit 1
          fi

      - name: Check testcase4.trace
        run: |
          if diff -q testcase4.trace testcase4_answer.trace; then
            echo "testcase4.trace success."
          else
            echo "testcase4.trace fail."
            exit 1
          fi

      # 새로운 테스트 케이스 5
      - name: Print testcase5.o diff
        run: diff testcase5.o testcase5_answer.o

      - name: Print testcase5.trace diff
        run: diff testcase5.trace testcase5_answer.trace

      - name: Check testcase5.o
        run: |
          if diff -q testcase5.o testcase5_answer.o; then
            echo "testcase5.o success."
          else
            echo "testcase5.o fail."
            exit 1
          fi

      - name: Check testcase5.trace
        run: |
          if diff -q testcase5.trace testcase5_answer.trace; then
            echo "testcase5.trace success."
          else
            echo "testcase5.trace fail."
            exit 1
          fi

      # 새로운 테스트 케이스 6
      - name: Print testcase6.o diff
        run: diff testcase6.o testcase6_answer.o

      - name: Print testcase6.trace diff
        run: diff testcase6.trace testcase6_answer.trace

      - name: Check testcase6.o
        run: |
          if diff -q testcase6.o testcase6_answer.o; then
            echo "testcase6.o success."
          else
            echo "testcase6.o fail."
            exit 1
          fi

      - name: Check testcase6.trace
        run: |
          if diff -q testcase6.trace testcase6_answer.trace; then
            echo "testcase6.trace success."
          else
            echo "testcase6.trace fail."
            exit 1
          fi

      # 새로운 테스트 케이스 7
      - name: Print testcase7.o diff
        run: diff testcase7.o testcase7_answer.o

      - name: Print testcase7.trace diff
        run: diff testcase7.trace testcase7_answer.trace

      - name: Check testcase7.o
        run: |
          if diff -q testcase7.o testcase7_answer.o; then
            echo "testcase7.o success."
          else
            echo "testcase7.o fail."
            exit 1
          fi

      - name: Check testcase7.trace
        run: |
          if diff -q testcase7.trace testcase7_answer.trace; then
            echo "testcase7.trace success."
          else
            echo "testcase7.trace fail."
            exit 1
          fi

          # 새로운 테스트 케이스 8-1
      - name: Print testcase8-1.o diff
        run: diff testcase8-1.o testcase8-1_ans.o

      - name: Print testcase8-1.trace diff
        run: diff testcase8-1.trace testcase8-1_ans.trace

      - name: Check testcase8-1.o
        run: |
          if diff -q testcase8-1.o testcase8-1_ans.o; then
            echo "testcase8-1.o success."
          else
            echo "testcase8-1.o fail."
            exit 1
          fi

      - name: Check testcase8-1.trace
        run: |
          if diff -q testcase8-1.trace testcase8-1_ans.trace; then
            echo "testcase8-1.trace success."
          else
            echo "testcase8-1.trace fail."
            exit 1
          fi

      # 새로운 테스트 케이스 8-2
      - name: Print testcase8-2.o diff
        run: diff testcase8-2.o testcase8-2_ans.o

      - name: Print testcase8-2.trace diff
        run: diff testcase8-2.trace testcase8-2_ans.trace

      - name: Check testcase8-2.o
        run: |
          if diff -q testcase8-2.o testcase8-2_ans.o; then
            echo "testcase8-2.o success."
          else
            echo "testcase8-2.o fail."
            exit 1
          fi

      - name: Check testcase8-2.trace
        run: |
          if diff -q testcase8-2.trace testcase8-2_ans.trace; then
            echo "testcase8-2.trace success."
          else
            echo "testcase8-2.trace fail."
            exit 1
          fi

      # 새로운 테스트 케이스 8-3
      - name: Print testcase8-3.o diff
        run: diff testcase8-3.o testcase8-3_ans.o

      - name: Print testcase8-3.trace diff
        run: diff testcase8-3.trace testcase8-3_ans.trace

      - name: Check testcase8-3.o
        run: |
          if diff -q testcase8-3.o testcase8-3_ans.o; then
            echo "testcase8-3.o success."
          else
            echo "testcase8-3.o fail."
            exit 1
          fi

      - name: Check testcase8-3.trace
        run: |
          if diff -q testcase8-3.trace testcase8-3_ans.trace; then
            echo "testcase8-3.trace success."
          else
            echo "testcase8-3.trace fail."
            exit 1
          fi